FROM node:22.8.0-slim

# Instalando ferramentas de desenvolvimento
RUN apt update && apt install -y curl && npm i -g nodemon

COPY start.sh /
RUN chmod +x /start.sh

# Criando usuário para não root
#RUN useradd -m -u 1097 application
#USER application 
USER node

WORKDIR /home/node/app

# cacheamento de camadas
COPY package.json ./
RUN npm install

COPY . .



# Informa a porta que a aplicação vai rodar
EXPOSE 4001

CMD ["/start.sh"]